
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- HYPRLAND CONFIG — Gruvbox Dark                         --
-- Based on the autogenerated template, restyled.         --
-- https://wiki.hypr.land/Configuring/Start/               --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
 
 
------------------
---- MONITORS ----
------------------
 
hl.monitor({
    mode     = "1920x1080@60.00",
    position = "0x0",
    scale    = "auto",
    output   = "eDP-1"
})

hl.dsp.exec_cmd("hyprctl dispatch moveworkspacetomonitor 1 pantalla")
---------------------
---- MY PROGRAMS ----
---------------------
 
local terminal    = "kitty"
local fileManager = "kitty --class ranger -e ranger"
local menu        = "rofi -show drun -config ~/.config/rofi/config.rasi"
 
 
-------------------
---- AUTOSTART ----
-------------------
 
hl.on("hyprland.start", function()
  hl.exec_cmd("systemctl --user start graphical-session.target")
end)
hl.dsp.exec_cmd("hyprpaper")
-- in startup/init section
hl.dsp.exec_cmd("[workspace 2 silent] firefox")
hl.dsp.exec_cmd("[workspace 1 silent] vesktop")
hl.dsp.exec_cmd("[workspace 3 silent] feishin")
-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------
 
hl.env("XCURSOR_THEME", "Capitaine Cursors (Gruvbox)")
hl.env("XCURSOR_SIZE", "16")
hl.env("HYPRCURSOR_THEME", "Capitaine Cursors (Gruvbox)")
hl.env("HYPRCURSOR_SIZE", "16")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")
hl.env("EDITOR", "vim")
hl.env("VISUAL", "vim")
-----------------------
---- LOOK AND FEEL ----
-----------------------
 
-- Gruvbox Dark palette
-- bg0 #282828  bg1 #3c3836  fg #ebdbb2
-- red #fb4934  green #b8bb26  yellow #fabd2f
-- blue #83a598  purple #d3869b  aqua #8ec07c
-- orange #fe8019  gray #928374
 
hl.config({
    general = {
        gaps_in  = 3,
        gaps_out = 9,
        border_size = 2,
        col = {
            active_border   = { colors = {"rgba(fabd2fff)", "rgba(fb9914ff)"}, angle = 45 },
            inactive_border = "rgba(3c3836aa)",
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },

    cursor = {
        no_hardware_cursors = true,
        inactive_timeout = 0.9386,
    },

    decoration = {
        rounding       = 9,
        rounding_power = 2,

        active_opacity   = 1.0,
        inactive_opacity = 0.93,

        shadow = {
            enabled      = true,
            range        = 14,
            render_power = 3,
            color        = 0xcc1d2021,
        },

        blur = {
            enabled   = true,
            size      = 4,
            passes    = 2,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})
 
-- Curves
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
 
hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })
 
hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })
 
hl.config({
    dwindle = {
        preserve_split = true,
    },
})
 
hl.config({
    master = {
        new_status = "master",
    },
})
 
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})
 
 
----------------
----  MISC  ----
----------------
 
hl.config({
    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo   = true,
    },
})
 
 
---------------
---- INPUT ----
---------------
 
hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",
 
        follow_mouse = 1,
 
        sensitivity = 0,
 
        touchpad = {
            natural_scroll = false,
        },
    },
})
 
hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})
 
 
---------------------
---- KEYBINDINGS ----
---------------------
 
local mainMod = "SUPER"
 
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("systemctl poweroff"))
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))
hl.bind("F1", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | swappy -f -"))

hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))
 
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end
 
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))
 
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))
 
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
 
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })
 
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })
 
 
--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------
 
hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },
 
    suppress_event = "maximize",
})
 
hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },
 
    no_focus = true,
})
 
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },
 
    move  = "20 monitor_h-120",
    float = true,
})
hl.window_rule({
    name  = "ranger-float",
    match = { class = "ranger" },
    float = true,
    size  = "900 600",
    move  = "510 240",
})
hl.window_rule({
    name  = "btop-float",
    match = { class = "btop" },
    float = true,
    size  = "1200 700",
    move  = "510 240",
})

