# Hyprlock — Gruvbox Dark
# Minimal: wallpaper visible, small clock, clean password input

general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 0
    no_fade_in = false
    no_fade_out = false
}

background {
    monitor =
    path = ~/Pictures/bossa.jpg 
    blur_passes = 0
    blur_size = 0
    brightness = 0.7
    contrast = 1.0
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}




# Password input
input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(fe8019ff)
    inner_color = rgba(282828ee)
    font_color = rgba(ebdbb2ff)
    fade_on_empty = true
    placeholder_text = <span foreground="##928374">󰌾  password</span>
    hide_input = false
    check_color = rgba(b8bb26ff)
    fail_color = rgba(fb4934ff)
    fail_text = <span foreground="##fb4934">$FAIL <b>($ATTEMPTS)</b></span>
    capslock_color = rgba(fabd2fff)
    position = 0, -80
    halign = center
    valign = center
    rounding = 8
}
